apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: nerdspaceaksacr.azurecr.io/logging:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: logging-svc
spec:
  selector:
    app: logging-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

